# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('to_whom', models.CharField(max_length=100)),
                ('what_is', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=10240)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
