# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition_info',
            name='signers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
