# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_petition_info_signers'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition_info',
            name='users',
            field=models.CharField(default='', max_length=10240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usernum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
